#!/bin/sh
refname="$1"
oldrev="$2"
newrev="$3"
git show $newrev > commitFile$newrev.txt
file=commitFile$newrev.txt
while read -r line
do
    if [[ "$line" == diff* ]] ; then toextract=false ; fi
    if [[ "$line" == @@* ]] ; then toextract=true ; fi 
    
    # content to be output to JS file
    if [ "$toextract" = true ] && [[ "$line" != @@* ]] && [[ "$line" != -* ]] ; then
        echo $line | sed 's/^.//'>> input.js  #remove first character
    fi

done < $file
